# https://www.phind.com/search?cache=uw30a1s89jaw9t13lrqbq633
name: CI/CD Pipeline

on:
  pull_request_target:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate deployment package
      run: zip -r ${{ github.run_id }}.zip . -x '*.git*'

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: test-2
        environment_name: Test-2-env
        region: ap-southeast-1
        version_label: ${{github.run_number}}
        deployment_package: ${{ github.run_id }}.zip
